/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-03-27 12:33:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class _04_005fpizza_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/today.jsp", Long.valueOf(1585304346985L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\ttable{border-collapse: collapse;}\r\n");
      out.write("\tth, td{border: 1px solid black;}\r\n");
      out.write("\t.label{display : inline-block; width: 70px;} \r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2>오늘은 <span style=\"color:pink\">");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 
		Date now = new Date();
		String today = String.format("%tY년 %tm월 %td일 %tA", now, now, now, now);
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print( today );
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</span> 입니다.</h2>\r\n");
      out.write("\r\n");
      out.write("<h2>피자 아카데미</h2>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>종류</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>가격</th>\r\n");
      out.write("\t\t\t<th rowspan=\"12\" width=\"10px\"> </th>\r\n");
      out.write("\t\t\t<th>종류</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>가격</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"5\">피자</td>\r\n");
      out.write("\t\t\t<td>치즈피자</td>\r\n");
      out.write("\t\t\t<td>5000</td>\r\n");
      out.write("\t\t\t<td rowspan=\"11\">사이드</td>\r\n");
      out.write("\t\t\t<td>오븐구이통닭</td>\r\n");
      out.write("\t\t\t<td>9000</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>콤비네이션피자</td>\r\n");
      out.write("\t\t\t<td>6000</td>\r\n");
      out.write("\t\t\t<td>치킨스틱&윙</td>\r\n");
      out.write("\t\t\t<td>4900</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>포테이토피자</td>\r\n");
      out.write("\t\t\t<td>7000</td>\r\n");
      out.write("\t\t\t<td>치즈오븐스파게티</td>\r\n");
      out.write("\t\t\t<td>4000</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>고구마피자</td>\r\n");
      out.write("\t\t\t<td>7000</td>\r\n");
      out.write("\t\t\t<td>새우링&웨지감자</td>\r\n");
      out.write("\t\t\t<td>3500</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>불고기피자</td>\r\n");
      out.write("\t\t\t<td>8000</td>\r\n");
      out.write("\t\t\t<td>갈릭포테이토</td>\r\n");
      out.write("\t\t\t<td>3000</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"6\">토핑</td>\r\n");
      out.write("\t\t\t<td>고구마무스</td>\r\n");
      out.write("\t\t\t<td>1000</td>\r\n");
      out.write("\t\t\t<td>콜라</td>\r\n");
      out.write("\t\t\t<td>1500</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>콘크림무스</td>\r\n");
      out.write("\t\t\t<td>1500</td>\r\n");
      out.write("\t\t\t<td>사이다</td>\r\n");
      out.write("\t\t\t<td>1500</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>파인애플토핑</td>\r\n");
      out.write("\t\t\t<td>2000</td>\r\n");
      out.write("\t\t\t<td>갈릭소스</td>\r\n");
      out.write("\t\t\t<td>500</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>치즈토핑</td>\r\n");
      out.write("\t\t\t<td>2000</td>\r\n");
      out.write("\t\t\t<td>피클</td>\r\n");
      out.write("\t\t\t<td>300</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>치즈크러스트</td>\r\n");
      out.write("\t\t\t<td>2000</td>\r\n");
      out.write("\t\t\t<td>핫소스</td>\r\n");
      out.write("\t\t\t<td>100</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>치즈바이트</td>\r\n");
      out.write("\t\t\t<td>3000</td>\r\n");
      out.write("\t\t\t<td>파마산 치즈가루</td>\r\n");
      out.write("\t\t\t<td>100</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"/2_JSP/04_pizzaEnd.do\">\r\n");
      out.write("\t\t<label for=\"pizza\" class=\"label\">피자 : </label>\r\n");
      out.write("\t\t<select name=\"pizza\">\r\n");
      out.write("\t\t\t<option value=\"치즈피자\">치즈피자</option>\r\n");
      out.write("\t\t\t<option value=\"콤비네이션피자\">콤비네이션피자</option>\r\n");
      out.write("\t\t\t<option value=\"포테이토피자\">포테이토피자</option>\r\n");
      out.write("\t\t\t<option value=\"고구마피자\">고구마피자</option>\r\n");
      out.write("\t\t\t<option value=\"불고기피자\">불고기피자</option>\r\n");
      out.write("\t\t</select><br>\r\n");
      out.write("\t\t<label class=\"label\">토핑 : </label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"topping\" value=\"고구마무스\">고구마무스</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"topping\" value=\"콘크림무스\">콘크림무스</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"topping\" value=\"파인애플토핑\">파인애플토핑</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"topping\" value=\"치즈토핑\">치즈토핑</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"topping\" value=\"치즈크러스트\">치즈크러스트</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"topping\" value=\"치즈바이트\">치즈바이트</label>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label class=\"label\">사이드 : </label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"오븐구이통닭\">오븐구이통닭</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"치킨스틱&윙\">치킨스틱&윙</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"치즈오븐스파게티\">치즈오븐스파게티</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"새우링&웨지감자\">새우링&웨지감자</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"갈릭포테이토\">갈릭포테이토</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"콜라\">콜라</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"사이다\">사이다</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"갈릭소스\">갈릭소스</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"피클\">피클</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"핫소스\">핫소스</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"side\" value=\"파마산 치즈가루\">파마산 치즈가루</label>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"확인\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
